### WHY USE NUMPY OVER LIST?

### 1. LESS MEMORY REQUIRED IN NUMPY ARRAY OVER LIST

In [64]:
import sys, numpy as np
li=[i for i in range(100)]
# print(*li)
# size of one element in list
print("List element size", sys.getsizeof(li[0]))
# size of all the elements of the list
print("List size", sys.getsizeof(li[0])*len(li))

np_arr=np.arange(100)
# print(np_arr)
# size of one element of np_arr
print("Numpy element size", np_arr.itemsize)
# size of all the elements of the np_arr
print("Numpy size", (np_arr.itemsize)*len(np_arr))

List element size 24
List size 2400
Numpy element size 4
Numpy size 400


### 2. LESS TIME REQUIRED

In [65]:
import time
import numpy as np
size=100000

# add two list
t1=time.time()
l1=[i for i in range(size)]
l2=[i for i in range(size)]
l3=[l1[i]+l2[i] for i in range(size)]
t2=time.time()
print((t2-t1)*1000)

# add two numpy arr
t1=time.time()
np1=np.arange(size)
np2=np.arange(size)
np3=np1+np2
t2=time.time()
print((t2-t1)*1000)

22.001981735229492
1.9984245300292969


In [31]:
import numpy as np

print("Array from List", np.array([4, 5, 6, 5]))
print("np.zeros()", np.zeros(3))
print("np.ones()", np.ones(3, dtype = int))
print("np.empty()", np.empty(5, dtype = int))
print("np.arrange()", np.arange(5))
print("np.arrange() in a range", np.arange(5, 10))
print("np.linspace", np.linspace(2, 6, 5))

Array from List [4 5 6 5]
np.zeros() [0. 0. 0.]
np.ones() [1 1 1]
np.empty() [5 6 7 8 9]
np.arrange() [0 1 2 3 4]
np.arrange() in a range [5 6 7 8 9]
np.linspace [2. 3. 4. 5. 6.]


In [66]:
arr = np.array([1, 2, 3, 4, 5])
print("Sort Array", np.sort(arr))

a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[5, 6, 7, 8, 9]])
print("Concatenate Arrays", np.concatenate((a, b), axis = 0))

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10]])
print("Concatenate Arrays", np.concatenate((a, b), axis = 1))
print("Dimension", a.ndim)
print("Shape", a.shape)
print("Size", a.size)

print("Reshape array", a.reshape((3, 2)))

Sort Array [1 2 3 4 5]
Concatenate Arrays [[1 2 3 4 5]
 [5 6 7 8 9]]
Concatenate Arrays [[ 1  2  3  7  8]
 [ 4  5  6  9 10]]
Dimension 2
Shape (2, 3)
Size 6
Reshape array [[1 2]
 [3 4]
 [5 6]]


In [74]:
import numpy as np

li_2d=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
np_2d=np.array(li_2d)
print("SLICING", np_2d[1,3])
print("SLICING", np_2d[:3,3])
print("SLICING", np_2d[2:,1:3])

SLICING 8
SLICING [ 4  8 12]
SLICING [[10 11]
 [14 15]]


In [75]:
import numpy as np
np1=np.arange(2,11,2)
print(np1)
a=np1>4
print(a)
print(np1[a])
print(np1[np1>4])
np1[np1>4]=7
print(np1)
print(np1[(np1>1) & (np1<7)])
print(np.where(np1==7))
np1[:2]=5
print(np1)

[ 2  4  6  8 10]
[False False  True  True  True]
[ 6  8 10]
[ 6  8 10]
[2 4 7 7 7]
[2 4]
(array([2, 3, 4], dtype=int64),)
[5 5 7 7 7]
